---
- name: Provision Jenkins servers
  hosts: jenkins
  become: yes
  ignore_unreachable: no

  tasks:
  - name: Install Java
    include_role:
      name: java

  - name: Install Jenkins
    include_role:
      name: jenkins
  
